;; Extract *spell-dictionary* values for known-spell-words generation
;; This script loads only the dictionary entries without the hook system
;; that isn't available in bloom-repl.

(load "tests/test-helpers.lisp")

;; Hash table for word overrides (garbled → correct)
(defvar *spell-dictionary* (make-hash-table))

;; Load the dictionary entries (copy from spell-translator.lisp)
(hash-set! *spell-dictionary* "abrahuyaqh" "artifact")
(hash-set! *spell-dictionary* "abraqpai" "archon")
(hash-set! *spell-dictionary* "abyzqh" "object")
(hash-set! *spell-dictionary* "aecandusiar" "adrenalin")
(hash-set! *spell-dictionary* "aepzguzz" "adhesion")
(hash-set! *spell-dictionary* "aiqpaf" "anchor")
(hash-set! *spell-dictionary* "aqqzrzgruhz" "accelerate")
(hash-set! *spell-dictionary* "aqueuq" "acidic")
(hash-set! *spell-dictionary* "bcandusahp" "breath")
(hash-set! *spell-dictionary* "eugwuggar" "dismissal")
(hash-set! *spell-dictionary* "ghcandusaw" "stream")
(hash-set! *spell-dictionary* "hiqahz" "locate")
(hash-set! *spell-dictionary* "hpkadawahjfouq" "thaumaturgic")
(hash-set! *spell-dictionary* "hxzrzz" "twelve")
(hash-set! *spell-dictionary* "hzggzgruqh" "tesseract")
(hash-set! *spell-dictionary* "izjfahanuq" "neurotoxic")
(hash-set! *spell-dictionary* "izjfahiouqar" "neurological")
(hash-set! *spell-dictionary* "izoahuzz" "negative")
(hash-set! *spell-dictionary* "jiyajudig" "unfocus")
(hash-set! *spell-dictionary* "ocandusagz" "grease")
(hash-set! *spell-dictionary* "oculoayunso" "deafen")
(hash-set! *spell-dictionary* "oculozur" "devil")
(hash-set! *spell-dictionary* "ouaih" "giant")
(hash-set! *spell-dictionary* "qafsacandusar" "corporeal")
(hash-set! *spell-dictionary* "qaiqzrrahuai" "cancellation")
(hash-set! *spell-dictionary* "qaiyjcandus" "conjure")
(hash-set! *spell-dictionary* "qpaiizr" "channel")
(hash-set! *spell-dictionary* "qzrzghuar" "celestial")
(hash-set! *spell-dictionary* "sagg" "pass")
(hash-set! *spell-dictionary* "saguhuzz" "positive")
(hash-set! *spell-dictionary* "sguaiuq" "psionic")
(hash-set! *spell-dictionary* "sraiabra" "planar")
(hash-set! *spell-dictionary* "sraojz" "plague")
(hash-set! *spell-dictionary* "tkadabfug" "kaubris")
(hash-set! *spell-dictionary* "uiygruzuguai" "infravision")
(hash-set! *spell-dictionary* "uizug" "invis")
(hash-set! *spell-dictionary* "unsopaiqzwunsoh" "enhancement")
(hash-set! *spell-dictionary* "waouq" "magic")
(hash-set! *spell-dictionary* "wugrzae" "mislead")
(hash-set! *spell-dictionary* "wunsohar" "mental")
(hash-set! *spell-dictionary* "wzhabaruq" "metabolic")
(hash-set! *spell-dictionary* "yawuruabra" "familiar")
(hash-set! *spell-dictionary* "yazfuz" "faerie")
(hash-set! *spell-dictionary* "yragp" "flesh")
(hash-set! *spell-dictionary* "zawsufuq" "vampiric")
(hash-set! *spell-dictionary* "zrzwunsohar" "elemental")
(hash-set! *spell-dictionary* "zuculaaruq" "vitriolic")

;; Output all dictionary values (one per line)
(do ((keys (hash-keys *spell-dictionary*) (cdr keys))) ((null? keys))
  (format #t "~A~%" (hash-ref *spell-dictionary* (car keys))))