;; tintin-save.lisp - Save/load state persistence for TinTin++ emulator
;;
;; Depends on: tintin-state.lisp, tintin-utils.lisp
;; ============================================================================
;; SAVE UTILITIES
;; ============================================================================
;; Escape string for Lisp syntax (backslashes first, then quotes)
(defun tintin-escape-string (str)
  (let ((result str))
    (set! result (string-replace result "\\" "\\\\")) ; Escape backslashes first
    (set! result (string-replace result "\"" "\\\"")) ; Then escape quotes
    result))

;; ============================================================================
;; STATE SAVING
;; ============================================================================
;; Save TinTin++ state to file
(defun tintin-save-state (filename)
  (let ((file (open filename "w")))
    ;; Write header
    (write-line file ";; TinTin++ State File")
    (write-line file ";; Generated by #save command")
    (write-line file "")
    ;; Write aliases
    (write-line file ";; Aliases")
    (let ((alias-entries (hash-entries *tintin-aliases*)))
      (do ((i 0 (+ i 1))) ((>= i (length alias-entries)))
        (let* ((entry (list-ref alias-entries i))
               (name (car entry))
               (value (cdr entry))
               (commands (car value))
               (priority (cadr value)))
          (write-line file
           (concat "(hash-set! *tintin-aliases* " "\""
            (tintin-escape-string name) "\" " "(list \""
            (tintin-escape-string commands) "\" " (number->string priority)
            "))")))))
    (write-line file "")
    ;; Write variables
    (write-line file ";; Variables")
    (let ((var-entries (hash-entries *tintin-variables*)))
      (do ((i 0 (+ i 1))) ((>= i (length var-entries)))
        (let* ((entry (list-ref var-entries i))
               (name (car entry))
               (value (cdr entry)))
          (write-line file
           (concat "(hash-set! *tintin-variables* " "\""
            (tintin-escape-string name) "\" " "\"" (tintin-escape-string value)
            "\")")))))
    (write-line file "")
    ;; Write highlights
    (write-line file ";; Highlights")
    (let ((highlight-entries (hash-entries *tintin-highlights*)))
      (do ((i 0 (+ i 1))) ((>= i (length highlight-entries)))
        (let* ((entry (list-ref highlight-entries i))
               (pattern (car entry))
               (data (cdr entry))
               (fg-color (car data))
               (bg-color (cadr data))
               (priority (caddr data)))
          (write-line file
           (concat "(hash-set! *tintin-highlights* " "\""
            (tintin-escape-string pattern) "\" " "(list "
            (if fg-color
              (concat "\"" (tintin-escape-string fg-color) "\"")
              "nil") " "
            (if bg-color
              (concat "\"" (tintin-escape-string bg-color) "\"")
              "nil") " " (number->string priority) "))")))))
    (write-line file "")
    ;; Write actions
    (write-line file ";; Actions")
    (let ((action-entries (hash-entries *tintin-actions*)))
      (do ((i 0 (+ i 1))) ((>= i (length action-entries)))
        (let* ((entry (list-ref action-entries i))
               (pattern (car entry))
               (data (cdr entry))
               (commands (car data))
               (priority (cadr data)))
          (write-line file
           (concat "(hash-set! *tintin-actions* " "\""
            (tintin-escape-string pattern) "\" " "(list \""
            (tintin-escape-string commands) "\" " (number->string priority)
            "))")))))
    (write-line file "")
    ;; Write settings
    (write-line file ";; Settings")
    (write-line file
     (concat "(set! *tintin-speedwalk-enabled* "
      (if *tintin-speedwalk-enabled* "#t" "#f") ")"))
    (write-line file
     (concat "(set! *tintin-speedwalk-diagonals* "
      (if *tintin-speedwalk-diagonals* "#t" "#f") ")"))
    (write-line file
     (concat "(set! *tintin-enabled* " (if *tintin-enabled* "#t" "#f") ")"))
    ;; Close file
    (close file)
    filename))

;; ============================================================================
;; COMMAND HANDLERS
;; ============================================================================
;; Handle #save command
;; args: (filename)
(defun tintin-handle-save (args)
  "Handle #save command (save TinTin++ state to file)."
  (let ((filename (tintin-strip-braces (list-ref args 0))))
    ;; Expand ~/path if present
    (set! filename (expand-path filename))
    (tintin-save-state filename)
    (tintin-echo (concat "State saved to '" filename "'\r\n"))
    ""))

;; Handle #load command
;; args: (filename)
(defun tintin-handle-load (args)
  "Handle #load command (load TinTin++ state from file)."
  (let ((filename (tintin-strip-braces (list-ref args 0))))
    ;; Expand ~/path if present
    (set! filename (expand-path filename))
    ;; Try to load the file, catching errors
    (if (condition-case err (progn (load filename) #t) (error #f))
      ;; Success case
      (progn (tintin-echo (concat "State loaded from '" filename "'\r\n")) "")
      ;; Error case
      (progn
        (tintin-echo
         (concat "Failed to load '" filename "': file not found or invalid\r\n"))
        ""))))
